### PR TITLE
Intrinsics support in the Sway compiler.

### PR DESCRIPTION
**Pull request by vaivaswatha**
Markdown version: https://github.com/FuelLabs/sway-rfcs/blob/vaivaswatha/intrinsics/rfcs/0003-intrinsics.md

### CODE REVIEW

**Comment by otrho** [comment]
Great.  This is a copy of the Google doc you made, so my comments remain the same, which is to say I agree with it. :slightly_smiling_face: 

It might be worth mentioning the possibility for Sway to target other backends (e.g., EVM) and so VM specific intrinsics (those which wrap low level instructions like `gas`) could/should be loaded/declared modularly.  The toolchain would get to choose which intrinsics are available based on the target.

And as mentioned, there's nothing stopping regular devs from using them so they'll need to be documented in a book, alongside the standard library I guess.

**Review by otrho — APPROVED** [review]
LGTM!

**Review by tritao — APPROVED** [review]
LGTM, all seems pretty reasonable.

**Review by mohammadfawaz — APPROVED** [review]
Nice and clear. Thanks!

**Review by sezna — APPROVED** [review]
I'm happy to see other backends mentioned. This is something we will be doing in the near future. Intrinsics allow us to move away from `asm` blocks, which essentially tie us to the FuelVM, and allow us to compile to alternate back ends. Commenting this here for posterity 😄

**Review by emilyaherbert — APPROVED** [review]
Looks great 👍  I agree with @sezna 's comment about other backends!

**Comment by vaivaswatha** [comment]
> Per request in [FuelLabs/sway#2771 (comment)](https://github.com/FuelLabs/sway/pull/2771#discussion_r972933679), I think we could improve on the table based approach suggested here with a function-level attribute instead. Basically, intrinsic functions will lack a body `{ ... }` + get annotated with `#[intrinsic]`. Example:
> 
> ```rust
> #[intrinsic]
> fn my_magic_intrinsic<ty_params>(params);
> ```
> 
> This will live in `core`, which is the only "crate" that is allowed to use `#[intrinsic]`. The attribute tells the type checker's check-part that _"there is no body, and that's OK, because that is defined elsewhere"_. The type checker will however implicitly trust that the signature collected visavi parameter types and type parameters (+ constraints) are accurate, so calls to intrinsics are type checked like any other function calls.
> 
> Optionally, we could have a table-like situation where intrinsic _definitions_ (**not calls**) are type checked, e.g., like `rustc` does, https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_typeck/check/intrinsic.rs.html

This will require type constraints (for example, `__add` is a polymorphic function whose type parameter is constrained to be an integer) which isn't implemented yet, but will soon be. But I like this approach overall.

**Pull request merged**
